#!/bin/zsh

# bash_config

# Make vim the default editor
export EDITOR="nvim"

# Default finder for neovim fzf
export FZF_DEFAULT_COMMAND="fd --type f"

# Ignore duplicate commands in the history
export HISTCONTROL=ignoredups

# Increase the maximum number of lines contained in the history file
# (default is 500)
export HISTFILESIZE=10000

# Increase the maximum number of commands to remember
# (default is 500)
export HISTSIZE=10000

# Make some commands not show up in history
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help"

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

export PATH=${PATH}:$HOME/.dotfiles/shell  # Current spotify song
export PATH="/opt/homebrew/bin:$PATH"

# Node Version Manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

###-tns-completion-start-###
if [ -f $HOME/.tnsrc ]; then
    source $HOME/.tnsrc
fi
###-tns-completion-end-###

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
# export PATH="$PATH:/Applications/Postgres.app/Contents/Versions/12/bin/"
# export PATH="/usr/local/sbin:$PATH"
# export PATH="/usr/local/opt/openjdk/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
# export PATH="$HOME/.rbenv/bin:$PATH"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

source "$HOME/.cargo/env"

# Redis Master
export PATH=/Users/Shared/DBngin/redis/7.0.0/bin:$PATH

# PostgreSQL
export PATH=/Users/Shared/DBngin/postgresql/15.1/bin:$PATH
# export PATH=/Users/Shared/DBngin/postgresql/14.3/bin:$PATH
# export PATH=/Applications/Postgres.app/Contents/Versions/16/bin:$PATH

export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@1.1/lib/pkgconfig"

export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"

export DISABLE_RSPEC_TIMEOUT=true
export DISABLE_SPRING=true
