# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export KEYTIMEOUT=1
source $HOME/.dotfiles/git/git_aliases # Git Aliases
source $HOME/.dotfiles/shell/shell_aliases # Shell Aliases
source $HOME/.dotfiles/shell/shell_exports # Shell Exports

if [[ -s "$HOME/.zshrc.local" ]]; then
  source $HOME/.zshrc.local # Customizations
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
